name: Module Testing Pipeline

on:
  workflow_dispatch:
    inputs:
      lang_branch:
        description: 'ballerina-lang branch'
        required: true
        default: 'master'
      downstream_branch:
        description: 'Downstream repository branch'
        required: false
        default: ''
      test_module:
        description: 'Test module (e.g., module-ballerina-io)'
        deprecationMessage: 'standard library module needs to be tested'
        required: true
        default: 'module-ballerina-io'

jobs:
  module-test-pipeline:
    name: Build Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python Packages
        run: |
          pip install requests
          pip install httplib2
          pip install colorama
          pip install configobj
          pip install requests

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 10.22.1

      - name: Build Modules
        shell: bash
        run: |
          if (${{ github.event.inputs.downstream_branch != ''}})
          then
            python -u dependabot/full_build_script.py ./ --lang-branch ${{ github.event.inputs.lang_branch }} \
            --update-stdlib-dependencies --test-module ${{ github.event.inputs.test_module }} \
            --downstream-branch ${{ github.event.inputs.downstream_branch }}
          else
            python -u dependabot/full_build_script.py ./ --lang-branch ${{ github.event.inputs.lang_branch }} \
            --update-stdlib-dependencies --test-module ${{ github.event.inputs.test_module }}
          fi
        env:
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
          devCentralToken: ${{ secrets.BALLERINA_DEV_CENTRAL_ACCESS_TOKEN }}
